packages:
  - 'packages/*'
  - 'examples/**/*'
  - '!examples/ssr/vite'
  - '!examples/ssr/vitepress'
  - '!examples/frameworks/nuxt3'
minimumReleaseAge: 1440
minimumReleaseAgeExclude:
  - '@kazupon/eslint-config'
  - vitest
  - '@vitest/mocker'
  - '@vitest/pretty-format'
  - '@vitest/snapshot'
  - '@vitest/spy'
  - '@vitest/runner'
  - '@vitest/expect'
  - '@vitest/utils'
  - '@vitest/coverage-v8'
