packages:
  - 'packages/*'
  - 'examples/**/*'
  - '!examples/ssr/vite'
  - '!examples/ssr/vitepress'
  - '!examples/frameworks/nuxt3'
minimumReleaseAge: 1440
minimumReleaseAgeExclude:
  - '@kazupon/eslint-config'
