packages:
  - 'packages/*'
  - 'examples/**/*'
  - '!examples/frameworks/nuxt3'
minimumReleaseAge: 1440
minimumReleaseAgeExclude:
  - vue
  - '@vue/compiler-dom'
  - '@vue/shared'
  - '@vue/runtime-vapor'
  - '@vue/server-renderer'
  - '@vue/compiler-sfc'
  - '@vue/runtime-dom'
  - '@vue/reactivity'
  - '@vue/compiler-vapor'
  - '@vue/compiler-ssr'
  - '@vue/runtime-core'
  - '@vue/compiler-core'
  - '@kazupon/eslint-config'
  - vitest
  - '@vitest/mocker'
  - '@vitest/pretty-format'
  - '@vitest/snapshot'
  - '@vitest/spy'
  - '@vitest/runner'
  - '@vitest/expect'
  - '@vitest/utils'
  - '@vitest/coverage-v8'
