name: Reproduire
on:
  issues:
    types: [labeled]

permissions:
  contents: read
  issues: write

jobs:
  reproduire:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5.0.1
        with:
          fetch-depth: 0
          persist-credentials: false
      - uses: Hebilicious/reproduire@a4b274773e3d6e8bef547385710473af11f5ec5d # v0.0.9-mp
        with:
          label: 'Status: Need More Info' # Optional, will default to this value.
