name: Size
on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - master
permissions:
  contents: read
  issues: write
env:
  CI: true

jobs:
  size:
    name: 'Size check'
    runs-on: ubuntu-latest
    env:
      CI_JOB_NUMBER: 1
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install pnpm
        uses: pnpm/action-setup@v2.0.1
        with:
          version: 6.15.1
      - name: Setup Node.js v16.x
        uses: actions/setup-node@v2
        with:
          node-version: 16
          cache: 'pnpm'
      - name: Install
        run: pnpm install
      - name: Check build size
        uses: posva/size-check-action@v1.1.2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          build_script: build:size
          files: packages/vue-i18n/dist/vue-i18n.global.prod.js packages/vue-i18n/dist/vue-i18n.runtime.global.prod.js packages/petite-vue-i18n/dist/petite-vue-i18n.global.prod.js packages/petite-vue-i18n/dist/petite-vue-i18n.runtime.global.prod.js packages/size-check-vue-i18n/dist/assets/index.js packages/size-check-petite-vue-i18n/dist/assets/index.js
